import { createClient } from "@/lib/supabase/server";

export default async function Billing({ searchParams }: { searchParams: Promise<Record<string,string|string[]|undefined>> }) {
  const params = await searchParams; const supabase = await createClient();
  const { data: claims } = await supabase.auth.getClaims(); const userId = claims?.claims?.sub!;
  const { data: profile } = await supabase.from("profiles").select("plan,mp_status,mp_subscription_id").eq("id", userId).single();
  const isPro = profile?.plan === "pro";
  const price = Number(process.env.PRO_PRICE_UYU || 199);
  return <div className="pageStack"><div><div className="eyebrow">SUSCRIPCIÓN</div><h1>PrintCost 3D Pro</h1><p className="muted">El cobro recurrente se procesa con Mercado Pago.</p></div>{params.limit && <div className="alert warn">Llegaste a las 5 cotizaciones del plan Free. Podés pasar a Pro para seguir guardando.</div>}{params.cancelled && <div className="alert ok">La suscripción fue cancelada.</div>}{params.error && <div className="alert error">{String(params.error)}</div>}{params.checkout && <div className="alert ok">Volviste del checkout. El plan se activa cuando Mercado Pago confirma la suscripción por webhook.</div>}<section className="billingGrid"><article className="panel planBox"><span className="pill">ACTUAL</span><h2>Free</h2><div className="bigPrice">$0</div><ul><li>5 cotizaciones por mes</li><li>Historial sincronizado</li><li>1 impresora inicial</li><li>Configuración de costos</li></ul></article><article className="panel planBox featuredPlan"><span className="pill">PRO</span><h2>Para makers que venden</h2><div className="bigPrice">${price} <small>UYU/mes</small></div><ul><li>Cotizaciones ilimitadas</li><li>Sin bloqueo mensual</li><li>Base preparada para más impresoras/materiales</li><li>Cancelación desde la app</li></ul>{isPro ? <><div className="statusBox">Plan activo · Mercado Pago: {profile?.mp_status || "authorized"}</div><form method="POST" action="/api/billing/cancel"><button className="dangerBtn full">Cancelar Pro</button></form></> : <form method="POST" action="/api/billing/subscribe"><button className="primary full">Pasar a Pro con Mercado Pago</button></form>}</article></section><section className="panel"><h2>Estado técnico</h2><p>Plan en base de datos: <b>{profile?.plan || "free"}</b>. Suscripción MP: <b>{profile?.mp_status || "sin iniciar"}</b>.</p></section></div>;
}
